version: "3.7"

services:
  messageboard:
    image: xguiga/messageboard:$version
    build:
      context: .
      cache_from:
        - xguiga/messageboard:latest
      args:
        GIT_TAG: $GIT_TAG
        GIT_COMMIT: $GIT_COMMIT
    environment:
      # Have user/password in the dockerfile is not a good idea
      # Should use secrets
      CREDENTIALS: guilherme:gui123,admin:back-challenge
      MESSAGES: /etc/messageboard/messages.csv
    networks:
      - back_network

networks:
  back_network:
