version: "3.7"

services:
  messageboard:
    image: xguiga/messageboard:$version
    build:
      context: .
      cache_from:
        - xguiga/messageboard:latest
      args:
        GIT_TAG: $GIT_TAG
        GIT_COMMIT: $GIT_COMMIT
    environment:
      # Have user/password in the dockerfile is not a good idea
      # Should use secrets
      CREDENTIALS: guilherme:gui123,admin:back-challenge
      MONGODB_URL: mongodb://mongodb
      MONGODB_INITIAL_CSV: /etc/messageboard/messages.csv
    ports:
      - target: 80
        published: 8080
        protocol: tcp
    networks:
      - back_network

  mongodb:
    image: mongo:3.6
    command: --bind_ip_all
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - back_network

volumes:
  mongodb-data:
  mongodb-config:

networks:
  back_network:
